factory/factory/urls.py
from django.contrib import admin
from django.urls import include, path

from factory1.views import product_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',product_list),
    path('factory1/', include('factory1.urls', namespace='factory1')),
    path('factory2/', include('factory2.urls', namespace='factory2')),

]

factory/factory1/urls.py
from django.urls import path
from . import views

app_name = 'factory1'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
]

factory/factory2/urls.py
from django.urls import path, re_path
from . import views

app_name = 'factory2'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    re_path(r'^product/(?P<product_id>\d+)/$', views.product_detail, name='product_detail1'),
]

factory/factory1/models.py
from django.db import models
from django.urls import reverse

class ConfectioneryFactoryproduct1(models.Model):
    name = models.CharField(max_length=255)
    category = models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    availability = models.BooleanField(default=True)
    creation_date = models.DateField(auto_now_add=True)
    description = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):

        return reverse('factory1:product_detail', args=(self.pk, ))

factory/factory2/models.py
from django.db import models
from django.urls import reverse


class ConfectioneryFactoryproduct2(models.Model):
    name = models.CharField(max_length=255)
    category = models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    availability = models.BooleanField(default=True)
    creation_date = models.DateField(auto_now_add=True)
    description = models.TextField()

    def __str__(self):
        return f'{self.name}'

factory/factory1/views.py
from django.shortcuts import render, get_object_or_404

from factory2.models import ConfectioneryFactoryproduct2
from .models import ConfectioneryFactoryproduct1

def product_list(request):
    factory2_products = ConfectioneryFactoryproduct2.objects.all()
    factory1_products = ConfectioneryFactoryproduct1.objects.all()
    return render(request, 'index.html', context={'factory2_products': factory2_products,'factory1_products': factory1_products})
def product_detail(request, product_id):
    product = get_object_or_404(ConfectioneryFactoryproduct1, id=product_id)
    return render(request, 'product_info.html', context={'product': product})

factory/factory2/views.py
from django.shortcuts import render, get_object_or_404
from .models import ConfectioneryFactoryproduct2
from factory1.models import ConfectioneryFactoryproduct1
def product_list(request):
    factory2_products = ConfectioneryFactoryproduct2.objects.all()
    factory1_products = ConfectioneryFactoryproduct1.objects.all()
    return render(request, 'index.html', context={'factory2_products': factory2_products,'factory1_products': factory1_products})

def product_detail(request, product_id):
    product = get_object_or_404(ConfectioneryFactoryproduct2, id=product_id)
    return render(request, 'product_info.html', context={'product': product})

factory/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Product List</title>
    <style>
        /* Стили для таблицы */
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
        }

        /* Стили для заголовков */
        h1, h2 {
            margin-top: 20px;
            margin-bottom: 10px;
        }
           a {
            color: #337ab7;
            text-decoration: none;
            transition: color 0.3s;
        }

        a:hover {
            color: #23527c;
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <h1>Product List</h1>
    <h2>Factory 1 Products</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Category</th>
                <th>Price</th>
                <th>Availability</th>
                <th>Creation Date</th>
                <th>Description</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            {% for product in factory1_products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.category }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.availability }}</td>
                <td>{{ product.creation_date }}</td>
                <td>{{ product.description }}</td>
                <td><a href="{{ product.get_absolute_url }}">Details</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h2>Factory 2 Products</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Category</th>
                <th>Price</th>
                <th>Availability</th>
                <th>Creation Date</th>
                <th>Description</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            {% for product in factory2_products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.category }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.availability }}</td>
                <td>{{ product.creation_date }}</td>
                <td>{{ product.description }}</td>
                <td><a href="{% url 'factory2:product_detail1' product.id %}">Details</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

factory/templates/product_info.html
<!DOCTYPE html>
<html>
<head>
    <title>Product Detail</title>
</head>
<body>
    <h1>Product Detail</h1>
    <table>
        <tr>
            <th>Name</th>
            <td>{{ product.name }}</td>
        </tr>
        <tr>
            <th>Category</th>
            <td>{{ product.category }}</td>
        </tr>
        <tr>
            <th>Price</th>
            <td>{{ product.price }}</td>
        </tr>
        <tr>
            <th>Availability</th>
            <td>{{ product.availability }}</td>
        </tr>
        <tr>
            <th>Creation Date</th>
            <td>{{ product.creation_date }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ product.description }}</td>
        </tr>
    </table>
</body>
</html>